# commenté pour utiliser les annotations
#home:
#    path: /
#    controller: App\Controller\HomeController::index
    
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout
    